const {test}=require('node:test'),assert=require('node:assert/strict');
const R=require('../rules-engine.js'),AI=require('../ai.js');
const u=(id,side,x,y,hero)=>({id,side,x,y,hero,type:hero?'hero':'soldier',name:id,alive:true});
function board(units,first='red'){const s=R.create(undefined,first);s.ply=6;s.units=units;return s;}
function quiet(s){for(const unit of s.units.filter(u=>u.alive&&u.side===s.side)){const move=R.legal(s,unit.id,'move')[0];if(move){R.apply(s,unit.id,'move',move);return;}}R.pass(s);}
function wait(s,n){for(let i=0;i<n;i++){assert.equal(s.winner,null);quiet(s);}}
test('more than three units never starts the endgame clock',()=>{const s=board([u('r','red',1,0),u('rr','red',1,3),u('b','blue',4,0),u('bb','blue',4,3)]);wait(s,25);assert.equal(s.winner,null);assert.equal(R.endgameInfo(s).active,false);});
test('19 complete turns do not end the game; turn 20 awards the larger army before hero priority',()=>{const s=board([u('r','red',1,0),u('rr','red',1,3),u('b','blue',4,3,'mage')]);wait(s,19);assert.deepEqual(R.endgameInfo(s),{active:true,steps:19,remaining:1});quiet(s);assert.equal(s.winner,'red');assert.equal(s.victoryReason,'material');assert.equal(R.endgameInfo(s).steps,20);assert.equal(s.phase,'over');assert.equal(R.legal(s,'r','move').length,0);assert.match(s.events.at(-1).text,/20 步检定/);});
for(const first of ['red','blue']){
  test(`one hero beats one soldier regardless of first player ${first}`,()=>{const s=board([u('r','red',1,0,'general'),u('b','blue',4,3)],first);wait(s,20);assert.equal(s.winner,'red');assert.equal(s.victoryReason,'hero');});
  for(const type of ['soldier','hero'])test(`same broad type ${type}: second player wins when ${first} starts`,()=>{const s=board([u('r','red',1,0,type==='hero'?'general':null),u('b','blue',4,3,type==='hero'?'mage':null)],first);wait(s,20);assert.equal(s.winner,first==='red'?'blue':'red');assert.equal(s.victoryReason,'second');});
}
test('the capture that creates a three-unit board starts at zero, then twenty further turns',()=>{const s=board([u('r','red',1,1,'general'),u('rr','red',1,3),u('b','blue',3,1),u('bb','blue',4,3,'mage')]);R.apply(s,'r','attack',R.legal(s,'r','attack').find(o=>o.target==='b'));assert.equal(s.ply,7);assert.equal(R.endgameInfo(s).steps,0);wait(s,19);assert.equal(s.winner,null);quiet(s);assert.equal(s.victoryReason,'material');});
test('capture from three to two does not reset an existing countdown',()=>{const s=board([u('r','red',1,1,'assassin'),u('b','blue',2,1),u('bb','blue',4,3,'mage')]);s.endgameStartPly=-4;R.apply(s,'r','attack',R.legal(s,'r','attack')[0]);assert.equal(R.endgameInfo(s).steps,11);wait(s,9);assert.equal(s.winner,'blue');assert.equal(s.victoryReason,'second');});
test('natural elimination on the last permitted turn takes priority over adjudication',()=>{const s=board([u('r','red',1,0),u('b','blue',3,1,'mage')]);s.endgameStartPly=-13;R.apply(s,'r','attack',R.legal(s,'r','attack')[0]);assert.equal(s.winner,'red');assert.equal(s.victoryReason,'elimination');});
test('a dodge and the original attacker follow-up count as only one turn',()=>{const s=board([u('r','red',1,1,'pikeman'),u('b','blue',3,1,'ranger'),u('bb','blue',4,3)]);R.apply(s,'r','attack',R.legal(s,'r','attack')[0]);assert.equal(R.endgameInfo(s).steps,0);R.apply(s,'b','move',R.legal(s,'b','move').find(o=>o.x===2&&o.y===1));assert.equal(R.endgameInfo(s).steps,0);R.apply(s,'r','attack',R.legal(s,'r','attack').find(o=>o.target==='b'));assert.equal(R.endgameInfo(s).steps,1);});
test('combo decisions do not consume multiple countdown turns',()=>{const s=board([u('r','red',1,1,'vanguard'),u('b','blue',3,1),u('bb','blue',5,1,'mage')]);R.apply(s,'r','attack',R.legal(s,'r','attack')[0]);assert.equal(s.phase,'combo');assert.equal(R.endgameInfo(s).steps,0);R.decline(s);assert.equal(R.endgameInfo(s).steps,1);});
test('forced passes count towards the same twenty-turn adjudication',()=>{const s=board([u('r','red',1,1,'strategist'),u('b','blue',3,1,'strategist')]);for(let i=0;i<20;i++){assert.equal(R.hasActions(s),false);R.pass(s);}assert.equal(s.winner,'blue');assert.equal(s.victoryReason,'second');});
test('AI keys distinguish first player and remaining adjudication time',()=>{const s=board([u('r','red',1,0),u('b','blue',4,3)]),t=JSON.parse(JSON.stringify(s));s.endgameStartPly=0;t.endgameStartPly=1;assert.notEqual(AI.key(s),AI.key(t));t.endgameStartPly=0;t.first='blue';assert.notEqual(AI.key(s),AI.key(t));});
