const {test}=require('node:test'),assert=require('node:assert/strict');
const AI=require('../ai.js'),R=require('../rules-engine.js'),L=require('../learning.js');
const profile=weights=>({schema:1,ruleVersion:'endgame-20-ply-v1',id:'fixture',version:1,weights});
function game(winner='red'){const f=Array(AI.FEATURE_NAMES.length).fill(0);f[0]=1;return {ruleVersion:'endgame-20-ply-v1',winner,trajectory:[{side:'red',base:0,features:f},{side:'blue',base:0,features:f.map(x=>-x)}]};}
test('training needs 20 labeled compatible games; unfinished games have no labels',async()=>{assert.equal((await L.fit(Array.from({length:19},()=>game()),null)).needed,1);const result=await L.fit(Array.from({length:30},()=>game(null)),null);assert.equal(result.candidate,null);assert.equal(result.games,0);});
test('outcome training changes weights in the expected direction and preserves its parent',async()=>{const parent=profile(Array(AI.FEATURE_NAMES.length).fill(0)),before=JSON.stringify(parent);const result=await L.fit(Array.from({length:20},()=>game()),parent);assert.ok(result.candidate.weights[0]>0);assert.equal(result.candidate.version,2);assert.equal(result.candidate.parentId,parent.id);assert.ok(AI.validProfile(result.candidate));assert.equal(JSON.stringify(parent),before);const opposite=await L.fit(Array.from({length:20},()=>game('blue')),parent);assert.ok(opposite.candidate.weights[0]<0);});
test('cancelled fitting never returns a candidate for activation',async()=>{const result=await L.fit(Array.from({length:20},()=>game()),null,{cancelled:()=>true});assert.equal(result.cancelled,true);assert.equal(result.candidate,null);});
test('invalid and incompatible profiles are rejected',()=>{for(const p of [profile([NaN]),profile(Array(AI.FEATURE_NAMES.length).fill(181)),{...profile([]),ruleVersion:'old'}])assert.throws(()=>AI.setProfile(p));AI.setProfile(null);});
test('learned parameters are consumed by evaluation and explicit search snapshots',async()=>{const state=R.create({red:['general','knight'],blue:['mage','dragon']}),weights=Array(AI.FEATURE_NAMES.length).fill(0);weights[0]=100;const p=profile(weights);const baseline=AI.evaluate(state,'red',null);assert.equal(AI.evaluate(state,'red',p),baseline+100);const limits={maxDepth:1,maxNodes:2500,timeMs:5000};const before=await AI.choose(state,{...limits,profile:null}),trained=await AI.choose(state,{...limits,profile:p});assert.equal(trained.stats.score,before.stats.score+100);AI.setProfile(p);assert.equal(AI.evaluate(state,'red'),baseline+100);assert.equal(AI.evaluate(state,'red',null),baseline);AI.setProfile(null);});
test('features change sign when perspective changes',()=>{const s=R.create({red:['general','knight'],blue:['mage','dragon']});const a=AI.features(s,'red'),b=AI.features(s,'blue');a.forEach((n,i)=>assert.ok(Math.abs(n+b[i])<1e-9));});
test('promotion requires full held-out validation, enough decisions, 60 percent and net four wins',()=>{assert.equal(L.passesGate({completed:20,wins:12,losses:8}),true);for(const stats of [{completed:19,wins:15,losses:4},{completed:20,wins:10,losses:10},{completed:20,wins:9,losses:5},{completed:20,wins:11,losses:9}])assert.equal(L.passesGate(stats),false);});
test('validation swaps candidate colors with matched rosters and records all games',async()=>{const candidate=profile(Array(AI.FEATURE_NAMES.length).fill(0)),original=AI.choose,records=[],seen=new Set();AI.choose=async(s,options)=>{seen.add(options.profile?.id??'baseline');return {action:AI.actions(s)[0]};};try{const stats=await L.validate(candidate,null,{onGame:async result=>records.push(result)});assert.equal(stats.completed,20);assert.equal(records.length,20);assert.deepEqual(records[0].rosters.red,records[1].rosters.blue);assert.deepEqual(records[0].rosters.blue,records[1].rosters.red);assert.equal(records[0].candidateSide,'red');assert.equal(records[1].candidateSide,'blue');assert.ok(seen.has('baseline')&&seen.has('fixture'));}finally{AI.choose=original;}});
